name: Bump version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Take last commit
        id: log
        run: echo "message=$(git log --no-merges -1 --oneline)" >> $GITHUB_OUTPUT
      - name: Take repository
        id: repo
        run: echo "message=$GITHUB_REPOSITORY" >> $GITHUB_OUTPUT
      - name: Bump version
        if: "!contains(steps.log.outputs.message, 'Bump version') && contains(steps.repo.outputs.message, 'YosysHQ/yosys')"
        run: |
          make bumpversion
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Makefile
          git commit -m "Bump version"
      - name: Push changes # push the output folder to your repo
        if: "!contains(steps.log.outputs.message, 'Bump version') && contains(steps.repo.outputs.message, 'YosysHQ/yosys')"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
